# **Análisis del Precio de la Acción de Apple**

Se analizara el precio de la acción de Apple para crear un modelo de predicción el cual sera evaluado con los datos reales del DataFrame. 

# **Carga de librerías y archivo**

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import os

In [3]:
df = pd.read_csv(r'C:\Users\danielortega\OneDrive - HOTELERA YALKUITO SA DE CV\Desktop\No Borrar Daniel\30 Data Analyst - Curso\52_Módulo_46_Series_de_Tiempo\Modulo_46_Tarea_Series_de_Tiempo\Analista de datos AAPL_2006-01-01_to_2018-01-01_M30.csv', 
                 index_col='Date', parse_dates=['Date'])

df.sample(5)

Open    High     Low   Close     Volume  Name
Date                                                       
2012-12-31   72.93   76.49   72.71   76.02  164872785  AAPL
2007-12-26   28.43   28.71   28.12   28.42  175933023  AAPL
2015-11-02  120.80  121.36  119.61  121.18   31761309  AAPL
2012-04-16   87.15   87.18   82.61   82.88  262696056  AAPL
2007-12-17   27.25   27.52   26.14   26.34  256172938  AAPL

In [4]:
df.head(3)

Open   High    Low  Close     Volume  Name
Date                                                   
2006-01-03  10.34  10.68  10.32  10.68  201853036  AAPL
2006-01-04  10.73  10.85  10.64  10.71  155225609  AAPL
2006-01-05  10.69  10.70  10.54  10.63  112396081  AAPL

In [5]:
df.tail(3)

Open    High     Low   Close    Volume  Name
Date                                                      
2017-12-27  170.10  170.78  169.71  170.60  21498213  AAPL
2017-12-28  171.00  171.85  170.48  171.08  16480187  AAPL
2017-12-29  170.52  170.59  169.22  169.23  25999922  AAPL

____

# **Análisis Univariado**

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3019 entries, 2006-01-03 to 2017-12-29
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Open    3019 non-null   float64
 1   High    3019 non-null   float64
 2   Low     3019 non-null   float64
 3   Close   3019 non-null   float64
 4   Volume  3019 non-null   int64  
 5   Name    3019 non-null   object 
dtypes: float64(4), int64(1), object(1)
memory usage: 165.1+ KB


In [7]:
df.nunique()

Open      2630
High      2579
Low       2575
Close     2579
Volume    3019
Name         1
dtype: int64

In [8]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [9]:
df.describe().T

count         mean          std         min         25%          50%  \
Open   3019.00        64.67        44.52        7.39       23.43        57.86   
High   3019.00        65.26        44.81        7.56       23.80        58.46   
Low    3019.00        64.03        44.23        7.17       23.02        57.32   
Close  3019.00        64.66        44.54        7.24       23.42        57.92   
Volume 3019.00 131145687.66 101855966.22 11475922.00 52928887.00 106627080.00   

                75%          max  
Open          99.16       175.11  
High         100.28       177.20  
Low           98.39       174.86  
Close         99.48       176.42  
Volume 179897651.50 843264044.00

In [10]:
df[df==0].count() / df.count()

Open     0.00
High     0.00
Low      0.00
Close    0.00
Volume   0.00
Name     0.00
dtype: float64

In [11]:
df.isnull().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
Name      0
dtype: int64

In [12]:
df.isna().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
Name      0
dtype: int64

In [13]:
df.shape

(3019, 6)

In [14]:
columnas = df.columns

for i in columnas:
    print(i)
    print(' ')
    print(df[i].unique())

Open
 
[ 10.34  10.73  10.69 ... 170.1  171.   170.52]
High
 
[ 10.68  10.85  10.7  ... 170.78 171.85 170.59]
Low
 
[ 10.32  10.64  10.54 ... 169.71 170.48 169.22]
Close
 
[ 10.68  10.71  10.63 ... 170.6  171.08 169.23]
Volume
 
[201853036 155225609 112396081 ...  21498213  16480187  25999922]
Name
 
['AAPL']
